NumPy assignment

In [121]:
#NumPy Retail Analytics Assignment
#Business Scenario
#You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.
#Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.
#You are provided with two main NumPy arrays:
#sales_data — monthly sales revenue generated by each store for different product categories.
#cost_data — total cost incurred by each store for the same product categories.
#Part 1: Dataset Creation
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


que-1:Array dimensions

In [122]:
#The finance manager wants to confirm how many stores and product categories are present in the data.

#Write NumPy code to display:

#Number of dimensions in sales_data
#Shape of sales_data
#Total number of values
#Data type of the array
#Memory occupied by the array


In [123]:
#Number of dimensions in sales_data
import numpy as np
np.ndim(sales_data)

2

In [124]:
##Shape of sales_data
np.shape(sales_data)

(5, 6)

In [125]:
#Total number of values
np.size(sales_data)

30

In [126]:
##Data type of the array
print(sales_data.dtype)

int64


In [127]:
#Memory occupied by the array
print(sales_data.nbytes,bytes)

240 <class 'bytes'>


Question 2: Store and Category Count

In [128]:
#Calculate the following:

#Total number of stores
#Total number of product categories
#Total number of store-category combinations

In [129]:
#Total number of stores
np.size(stores)

5

In [130]:
#Total number of product categories
np.size(categories)

6

In [131]:
#Total number of store-category combinations
np.size(stores)*np.size(categories)

30

Question 3: Sales Data Type Conversion

In [132]:
#The reporting application requires sales values in floating-point format.
#Convert sales_data into:
#float32
#float64
#Compare the memory used by both arrays.

In [133]:
#float32
sales_data.astype("float32")

array([[ 850000.,  420000.,  310000.,  275000.,  190000.,  225000.],
       [ 780000.,  460000.,  295000.,  310000.,  210000.,  240000.],
       [ 920000.,  390000.,  340000.,  260000.,  185000.,  215000.],
       [1050000.,  510000.,  375000.,  345000.,  250000.,  290000.],
       [ 690000.,  405000.,  280000.,  225000.,  175000.,  205000.]],
      dtype=float32)

In [134]:
#float64
sales_data.astype("float64")

array([[ 850000.,  420000.,  310000.,  275000.,  190000.,  225000.],
       [ 780000.,  460000.,  295000.,  310000.,  210000.,  240000.],
       [ 920000.,  390000.,  340000.,  260000.,  185000.,  215000.],
       [1050000.,  510000.,  375000.,  345000.,  250000.,  290000.],
       [ 690000.,  405000.,  280000.,  225000.,  175000.,  205000.]])

In [135]:
#Compare the memory used by both arrays.
print(sales_data.astype("float32").nbytes)
print(sales_data.astype("float64").nbytes)

120
240



Part 3: Indexing and Data Extraction

#Question 4: Bengaluru Store Analysis

In [136]:

#The Bengaluru regional manager wants to review sales for all product categories.
bengaluru_sales=sales_data[0]
print("bengaluru_sales: ")
print(bengaluru_sales)

bengaluru_sales: 
[850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis

In [137]:
#Extract the total cost incurred by the Mumbai store for all product categories.
total_cost=np.sum(cost_data,axis=1)
print("total_mumbai_cost:",total_cost[3])

total_mumbai_cost: 2065000


Question 6: Electronics Sales Across Stores

In [138]:
#The electronics department wants to compare its sales performance across all five stores.
#Extract the Electronics sales column from sales_data.
electronic_sales=sales_data[:,0]
print(electronic_sales)

[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores

In [139]:
#Extract the Clothing cost for every store from cost_data.

In [140]:
clothing_cost=cost_data[:,2]
print(clothing_cost)

[220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance


In [141]:
#Find the following for Hyderabad:
#Furniture sales
#Furniture cost
#Furniture profit

In [142]:
furniture_sales=sales_data[1,3]
furniture_cost=cost_data[1,3]
furniture_profit=furniture_sales-furniture_cost
print("furniture_sales:",furniture_sales)
print("furniture_cost:",furniture_cost)
print("furniture_profit:",furniture_profit)

furniture_sales: 310000
furniture_cost: 225000
furniture_profit: 85000


Question 9: Chennai Category Range

In [143]:
#Extract Chennai’s sales for the following categories:
#Groceries
#Clothing
#Furniture
#Use array slicing.



In [144]:
chennai_sales=sales_data[2,1:4]
groceries_sales=sales_data[2,1]
clothing_sales=sales_data[2,2]
furniture_sales=sales_data[2,3]
print("groceries_sales:",groceries_sales)
print("clothing_sales:",clothing_sales)
print("furniture_sales:",furniture_sales)

groceries_sales: 390000
clothing_sales: 340000
furniture_sales: 260000


In [145]:
#Question 10: Selected Store Analysis

#Question:
#Extract sales data for:

#Bengaluru
#Chennai
#Pune

#Include only:

#Electronics
#Clothing
#Beauty

#Use advanced indexing.
selected_sales = sales_data[[0, 2, 4]][:, [0, 2, 4]]
print("Selected Sales Data:")
print(selected_sales)

Selected Sales Data:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [146]:
#Calculate the total sales revenue generated by all stores and all product categories.
total_sales = np.sum(sales_data)
print("Total Company Sales:", total_sales)

Total Company Sales: 11675000


Question 12: Store-Wise Sales

In [147]:
store_sales = np.sum(sales_data, axis=1)
for i in range(len(stores)):
    print(stores[i], ":", store_sales[i])

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


In [148]:
# Calculate total sales for each product category
category_sales = np.sum(sales_data, axis=0)
for i in range(len(categories)):
    print(categories[i], ":", category_sales[i])

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


In [149]:
#Question
#Calculate the average sales generated by each store across all six product categories.
average_sales = np.mean(sales_data, axis=1)
print("Stores:")
print(stores)
print("Average Sales:")
print(average_sales)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
Average Sales:
[378333.33333333 382500.         385000.         470000.
 330000.        ]


In [150]:
# Calculate average sales for each product category
average_category_sales = np.mean(sales_data, axis=0)
print("Average Sales Per Category:")
print(average_category_sales)

Average Sales Per Category:
[858000. 437000. 320000. 283000. 202000. 235000.]


Question 16: Highest-Selling Store

In [151]:
## Calculate total sales of each store
store_sales = np.sum(sales_data, axis=1)
highest_index = np.argmax(store_sales)
print("Store Index:", highest_index)
print("Store Name:", stores[highest_index])
print("Total Sales:", store_sales[highest_index])

Store Index: 3
Store Name: Mumbai
Total Sales: 2820000


In [152]:
# Calculate total sales of each store
store_sales = np.sum(sales_data, axis=1)
lowest_index = np.argmin(store_sales)
print("Store Index:", lowest_index)
print("Store Name:", stores[lowest_index])
print("Total Sales:", store_sales[lowest_index])

Store Index: 4
Store Name: Pune
Total Sales: 1980000


Question 18: Highest-Selling Category

In [153]:
category_sales = np.sum(sales_data, axis=0)
highest_category = np.argmax(category_sales)
print("Category Index:", highest_category)
print("Category Name:", categories[highest_category])
print("Total Sales:", category_sales[highest_category])

Category Index: 0
Category Name: Electronics
Total Sales: 4290000


Question 19: Lowest-Selling Category

In [154]:
category_sales = np.sum(sales_data, axis=0)
lowest_category = np.argmin(category_sales)
print("Category Index:", lowest_category)
print("Category Name:", categories[lowest_category])
print("Total Sales:", category_sales[lowest_category])

Category Index: 4
Category Name: Beauty
Total Sales: 1010000


Question 20: Total Company Cost

In [155]:
#Question
#Calculate the total cost incurred by SmartMart across all stores and all product categories.
total_cost = np.sum(cost_data)
print("Total Company Cost:", total_cost)

Total Company Cost: 8600000


Question 21: Store-Wise Cost

In [156]:
# Calculate total cost for each store
store_cost = np.sum(cost_data, axis=1)
print("Store Wise Cost:")
print(store_cost)

Store Wise Cost:
[1665000 1685000 1710000 2065000 1475000]


In [157]:
# Calculate total cost for each category
category_cost = np.sum(cost_data, axis=0)
print("Category Wise Cost:")
print(category_cost)

Category Wise Cost:
[3250000 1660000 1145000 1045000  665000  835000]


Question 23: Most Expensive Store

In [158]:
# Calculate total cost of each store
store_cost = np.sum(cost_data, axis=1)
highest_cost = np.argmax(store_cost)
print("Store Index:", highest_cost)
print("Store Name:", stores[highest_cost])
print("Total Cost:", store_cost[highest_cost])

Store Index: 3
Store Name: Mumbai
Total Cost: 2065000


Question 24: Lowest-Cost Store

In [159]:
# Calculate total cost of each store
store_cost = np.sum(cost_data, axis=1)
lowest_cost = np.argmin(store_cost)
print("Store Index:", lowest_cost)
print("Store Name:", stores[lowest_cost])
print("Total Cost:", store_cost[lowest_cost])

Store Index: 4
Store Name: Pune
Total Cost: 1475000


Question 25: Most Expensive Product Category

In [160]:
# Calculate total cost of each category
category_cost = np.sum(cost_data, axis=0)
highest_category = np.argmax(category_cost)
print("Category Index:", highest_category)
print("Category Name:", categories[highest_category])
print("Total Cost:", category_cost[highest_category])

Category Index: 0
Category Name: Electronics
Total Cost: 3250000


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix

In [161]:
#Calculate the profit generated for every store and product category.
#Use:
#profit_data = sales_data - cost_data
#Display the complete profit matrix.
profit_data=(sales_data-cost_data)
print("profit_matrix:")
print(profit_data)




profit_matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [162]:
#Question 27: Store-Wise Profit
#Calculate the total profit generated by each store.
profit_data=(sales_data-cost_data)
store_wise_profit=np.sum(profit_data,axis=1)
print(store_wise_profit)

[605000 610000 600000 755000 505000]


In [163]:
#Question 28: Category-Wise Profit
#Calculate the total profit generated by each product category.
profit_data=(sales_data-cost_data)
category_wise_profit=np.sum(profit_data,axis=0)
print(category_wise_profit)

[1040000  525000  455000  370000  345000  340000]


In [164]:
#Question 29: Most Profitable Store
#Identify the store that generated the highest total profit.
#Display:
#Store name
#Total sales
#Total cost
#Total profit
store_profit=np.sum(sales_data-cost_data,axis=1)
index=np.argmax(store_profit)
print("store_name:",stores[index])
print("total_sales:",np.sum(sales_data[index]))
print("total_cost:",np.sum(cost_data[index]))
print("total_profit:",store_profit[index])

store_name: Mumbai
total_sales: 2820000
total_cost: 2065000
total_profit: 755000


In [165]:
#Question 30: Least Profitable Store
#Identify the store that generated the lowest total profit.
store_profit=np.sum(sales_data-cost_data,axis=1)
index=np.argmin(store_profit)
print("least_profitable_store:",stores[index])

least_profitable_store: Pune


In [166]:
#Question 31: Most Profitable Category
#Find the category with the highest total profit across all stores.
category_profit=np.sum(sales_data-cost_data,axis=0)
index=np.argmax(category_profit)
print("most_profitable_category:",categories[index])

most_profitable_category: Electronics


In [167]:
#Question 32: Least Profitable Category
#Find the category with the lowest total profit.
category_profit=np.sum(sales_data-cost_data,axis=0)
index=np.argmin(category_profit)
print("least_profitable_category:",categories[index])

least_profitable_category: Sports


In [168]:
#Question 33: Maximum Individual Profit
#Find the highest profit generated by any single store-category combination.
#Display:
#Profit amount
#Store name
#Product category
#Use np.unravel_index().
import numpy as np
profit_data=(sales_data-cost_data)
max_profit=np.max(profit_data)
index=np.argmax(profit_data)
row,col=np.unravel_index(index,profit_data.shape)
print("max_profit:",max_profit)
print("store_name:",stores[row])
print("product_category:",categories[col])

max_profit: 260000
store_name: Mumbai
product_category: Electronics


In [169]:
#Question 34: Minimum Individual Profit
#Find the smallest profit generated by a store-category combination.
#Display the corresponding store and category.
min_profit=np.min(profit_data)
index=np.argmin(profit_data)
row,col=np.unravel_index(index,profit_data.shape)
print("min_profit:",min_profit)
print("store:",stores[row])
print("category:",categories[col])


min_profit: 55000
store: Pune
category: Furniture


Part 7: Profit Margin Analysis

In [170]:
#Question 35: Profit Margin Matrix
#Calculate the profit margin percentage for every store-category combination.
#Use:
#profit_margin = (profit_data / sales_data) * 100
#Round the result to two decimal places.
profit_margin=(profit_data/sales_data)*100
profit_margin=np.round(profit_margin,2)
print("profit_margin_matrix:")
print(profit_margin)

profit_margin_matrix:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [171]:
#Question 36: Store-Wise Profit Margin
#Calculate the overall profit margin percentage for each store using:
#Store Profit Margin =
#Total Store Profit / Total Store Sales × 100
store_profit=np.sum(profit_data,axis=1)
store_sales=np.sum(sales_data,axis=1)
store_profit_margin=(store_profit/store_sales)*100
print("store_wise_profit_margin:")
print(store_profit_margin)


store_wise_profit_margin:
[26.65198238 26.5795207  25.97402597 26.77304965 25.50505051]


In [172]:
#Question 37: Category-Wise Profit Margin
#Calculate the overall profit margin percentage for each product category.
category_profit=np.sum(profit_data,axis=0)
category_sales=np.sum(sales_data,axis=0)
category_profit_margin=(category_profit/category_sales)*100
category_profit_margin=np.round(category_profit_margin,2)
print("category_wise_profit_margin:")
print(category_profit_margin)

category_wise_profit_margin:
[24.24 24.03 28.44 26.15 34.16 28.94]


In [173]:
#Question 38: Best Store by Profit Margin
#Identify the store with the highest overall profit margin.
store_profit=np.sum(profit_data,axis=1)
store_sales=np.sum(sales_data,axis=1)
store_profit_margin=(store_profit/store_sales)*100
index=np.argmax(store_profit_margin)
print("store_highest_profit:",stores[index])
print("profit_margin:",round(store_profit_margin[index],2))

store_highest_profit: Mumbai
profit_margin: 26.77


In [174]:
#Question 39: Best Category by Profit Margin
#Identify the product category with the highest profit margin.
category_profit=np.sum(profit_data,axis=0)
category_sales=np.sum(sales_data,axis=0)
category_profit_margin=(category_profit/category_sales)*100
index=np.argmax(category_profit_margin)
print("category_highest_profit:",categories[index])
print("profit_margin:",round(category_profit_margin[index],2))

category_highest_profit: Beauty
profit_margin: 34.16


In [175]:
#Question 40: Low-Margin Transactions
#Management considers a profit margin below 22% to be weak.
#Find all store-category combinations where the profit margin is below 22%.
#Display:
#Store
#Category
#Sales
#Cost
#Profit
#Profit margin
#Use Boolean indexing.
import numpy as np
profit_margin=(profit_data/sales_data)*100
low_margin=profit_margin<22
rows,cols=np.where(low_margin)
for r,c in zip(rows,cols):
  print("store:",stores[r])
  print("category:",categories[c])
  print("sales:",sales_data[r,c])
  print("cost:",cost_data[r,c])
  print("profit:",profit_data[r,c])
  print("profit_margin:",(profit_margin[r,c],2),"%")
  print()




Part 8: Boolean Filtering

In [176]:
#Question 41: High Sales Values
#Find all sales values greater than ₹5,00,000.
high_sales=sales_data[sales_data>500000]
print(high_sales)

[ 850000  780000  920000 1050000  510000  690000]


In [177]:
#Question 42: Low Sales Values
#Find all sales values below ₹2,00,000.
low_sales=sales_data[sales_data<200000]
print(low_sales)

[190000 185000 175000]


In [178]:
#Question 43: High Profit Values
#Find all store-category combinations where profit is greater than ₹1,50,000.
profit=sales_data-cost_data
high_profit= profit>150000
rows,col=np.where(high_profit)
for r,c in zip(rows,col):
  print("store:",stores[r])
  print("category:",categories[c])

store: Bengaluru
category: Electronics
store: Hyderabad
category: Electronics
store: Chennai
category: Electronics
store: Mumbai
category: Electronics
store: Pune
category: Electronics


In [179]:
#Question 44: Moderate Sales Range
#Find sales values between ₹2,50,000 and ₹5,00,000.
#Use np.logical_and().
import numpy as np
premium=np.logical_and(
    sales_data>500000,
    profit>150000
)
rows,cols=np.where(premium)
for r,c in zip(rows,cols):
  print("store:",stores[r])
  print("category:",categories[c])

store: Bengaluru
category: Electronics
store: Hyderabad
category: Electronics
store: Chennai
category: Electronics
store: Mumbai
category: Electronics
store: Pune
category: Electronics


In [180]:
#Question 45: Premium Performance
#A store-category combination is considered premium when:
#Sales are greater than ₹5,00,000
#Profit is greater than ₹1,50,000
#Find all premium-performing combinations.
profit=sales_data - cost_data
premium=np.logical_and(sales_data > 500000,profit > 150000)
store_index,category_index=np.where(premium)
# for i,j in zip(store_index,category_index):
#   print("store:",stores[i])
#   print("category:",categories[j])
#   print("sales:",sales_data[i,j])
#   print("profit:",profit[i,j])
print(sales_data[store_index,category_index])
print(profit[store_index,category_index])


[ 850000  780000  920000 1050000  690000]
[210000 190000 220000 260000 160000]


In [181]:
#Question 46: Underperforming Combinations
#A store-category combination is considered underperforming when:
#Sales are below ₹2,50,000
#Profit margin is below 25%
#Find all such combinations.
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
underperforming=np.logical_and(sales_data < 250000,profit_margin < 25)
store_index,category_index=np.where(underperforming)
for i,j in zip(store_index,category_index):
  print("store:",stores[i])
  print("category:",categories[j])
  print("profit:",profit[i,j])
  print("sales:",sales_data[i,j])
  print("profit_margin:",profit_margin[i,j])

store: Pune
category: Furniture
profit: 55000
sales: 225000
profit_margin: 24.444444444444443


In [182]:
#Question 47: Category Performance Classification
#Create a new array that classifies every sales value as:
#"High" when sales are at least ₹5,00,000
#"Medium" when sales are between ₹2,50,000 and ₹4,99,999
#"Low" when sales are below ₹2,50,000
#Use np.where() or np.select().
classification=np.where(
    sales_data >= 500000,
    "high",np.where((sales_data >= 250000) & (sales_data <499999),"medium","low"))

print(classification)


[['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'high' 'medium' 'medium' 'medium' 'medium']
 ['high' 'medium' 'medium' 'low' 'low' 'low']]


Part 9: Target-Based Analysis

In [183]:
import numpy as np
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [184]:
#Question 48: Target Comparison
#Compare every store’s category sales against sales_targets.
#Use NumPy broadcasting.
print(sales_data>=sales_targets)
# print(sales_data<=sales_targets)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [185]:
#Question 49: Target Achievement Matrix
#Create a Boolean array where:
#True means the store achieved the category target
#False means the store failed to achieve the target
target_reached=np.where(sales_data>sales_targets,True,False)
print(target_reached)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [186]:
#Question 50: Target Achievement Count
#Calculate the number of categories in which each store achieved its target.
target=np.sum(sales_data>=sales_targets,axis=1)
for store,count in zip(stores,target):
  print(store,":",count)

Bengaluru : 1
Hyderabad : 4
Chennai : 2
Mumbai : 6
Pune : 0


In [187]:
#Question 51: Best Target-Performing Store
#Find the store that achieved the highest number of category targets.
target=np.sum(sales_data>=sales_targets,axis=1)
target_index=np.argmax(target)
store_name=stores[target_index]
print(store_name)
print(target[target_index])

Mumbai
6


In [188]:
#Question 52: Target Achievement by Category
#Calculate how many stores achieved the target for each product category.
target=np.sum(sales_data>=sales_targets,axis=0)
for category,count in zip(categories,target):
  print(category,":",count)

Electronics : 3
Groceries : 2
Clothing : 2
Furniture : 2
Beauty : 2
Sports : 2


In [189]:
#Question 53: Sales Target Variance
#Calculate the difference between actual sales and target sales for every store.
#Use:
#Variance = Actual Sales - Target Sales
variance=sales_data-sales_targets
for i in variance:
  print(i)

[ 50000 -30000 -10000 -25000 -10000  -5000]
[-20000  10000 -25000  10000  10000  10000]
[120000 -60000  20000 -40000 -15000 -15000]
[250000  60000  55000  45000  50000  60000]
[-110000  -45000  -40000  -75000  -25000  -25000]


In [190]:
#Question 54: Percentage Above or Below Target
#Calculate the percentage variance from the target using:
#Percentage Variance =
#(Actual Sales - Target Sales) / Target Sales × 100
percentage_variance=(sales_data-sales_targets)/(sales_targets)*100
for i in percentage_variance:
  print(i)

[ 6.25       -6.66666667 -3.125      -8.33333333 -5.         -2.17391304]
[-2.5         2.22222222 -7.8125      3.33333333  5.          4.34782609]
[ 15.         -13.33333333   6.25       -13.33333333  -7.5
  -6.52173913]
[31.25       13.33333333 17.1875     15.         25.         26.08695652]
[-13.75       -10.         -12.5        -25.         -12.5
 -10.86956522]


In [191]:
#Question 55: Stores Missing Electronics Target
#Identify stores that failed to achieve the Electronics sales target.
electronic_sales=sales_data[:,0]
electronic_sales_targets=sales_targets[0]
missing_target=electronic_sales<electronic_sales_targets
for store,result in zip(stores,missing_target):
  if result:
    print(store)

Hyderabad
Pune


In [192]:
#Question 56: Stores Achieving All Targets
#Check whether any store achieved its target in all six product categories.
#Use np.all().
#store_target=np.all(sales_data >= sales_targets,axis=1)
for i,j in zip(stores,store_target):
  if  j:
    print(i)

NameError: name 'store_target' is not defined

In [ ]:
#Question 57: Stores Achieving At Least One Target
#Identify stores that achieved at least one category target.
#Use np.any().
#store_target=np.any(sales_data >= sales_targets,axis=1)
for i,j in zip(stores,store_target):
  if  j:
    print(i)

Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

In [ ]:
import numpy as np
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [ ]:
#Question 58: Discount Amount Matrix
#Calculate the discount amount for each store-category combination.
#Use broadcasting.
discount_amount = sales_data * discount_rates
print(np.round(discount_amount,2))


In [ ]:
#Question 59: Sales After Discount
#Calculate the net sales value after applying the category-wise discounts
discount_amount = sales_data * discount_rates
net_sales_value=sales_data-discount_amount
print(net_sales_value)

In [ ]:
#Question 60: Profit After Discount
#Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
discount_amount = sales_data * discount_rates
net_sales_value=sales_data-discount_amount
new_profit=net_sales_value-cost_data
print(new_profit)

In [ ]:
#Question 61: Profit Margin After Discount
#Calculate the new profit margin after applying discounts.
discount_amount = sales_data * discount_rates
net_sales_value = sales_data - discount_amount
new_profit = net_sales_value - cost_data
new_margin = (new_profit / net_sales_value) * 100
print(np.round(new_margin, 2))

In [ ]:
#Question 62: Loss-Making Transactions
#Check whether any store-category combination becomes loss-making after discounts.
#Display the affected store and category names.
discount_amount=sales_data*discount_rates
net_sales_values=sales_data-discount_amount
loss=np.where(net_sales_values < cost_data)
if loss[0].size > 0:
  print('Loss-making transactions found:')
  for i,j in zip(loss[0],loss[1]):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Net Sales: {net_sales_values[i,j]:.2f}, Cost: {cost_data[i,j]:.2f}")
else:
  print('No loss-making transactions found after discounts.')

In [ ]:
#Question 63: Discount Impact
#Calculate how much total revenue the company loses because of the proposed discounts.
discount_amount=sales_data*discount_rates
total_revenue_lost = np.sum(discount_amount)
print(f"Total revenue lost due to discounts: {total_revenue_lost:.2f}")

In [193]:

print(discount_amount)

NameError: name 'discount_amount' is not defined

In [ ]:
#Question 64: Store Most Affected by Discounts
#Identify the store that loses the highest amount of revenue due to discounts.
discount=np.sum(sales_data*discount_rates,axis=1)
max_discount=np.argmax(discount)
store_name=stores[max_discount]
print(store_name)
print(discount[max_discount])



Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

In [ ]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [ ]:
#Question 65: Tax Collection Matrix
#Calculate the tax collected on sales for each store and category.
tax=sales_data*tax_rates
print(tax)

In [ ]:
#Question 66: Sales Including Tax
#Calculate the final customer billing value after adding tax.
tax=sales_data*discount_rates
print(cost_data+tax)

In [194]:
#Question 67: Store-Wise Tax Collection
#Calculate the total tax collected by each store.
tax_store=np.sum(sales_data*tax_rates,axis=1)
print(tax_store)

[321900. 321200. 331800. 401400. 274650.]


In [195]:
#Question 68: Category-Wise Tax Collection
#Calculate total tax collected for each category.
tax=np.sum(sales_data*tax_rates,axis=0)
print(tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


In [196]:
#Question 69: Highest Tax-Contributing Store
#Identify the store that contributes the highest tax amount
tax=np.sum(sales_data*tax_rates,axis=1)
max_tax_store=np.argmax(tax)
print(max_tax_store)
print(stores[max_tax_store])

3
Mumbai


Part 12: Array Modification

In [197]:
#Question 70: Updated Pune Electronics Sales
#The Pune store reports that its Electronics sales were entered incorrectly.
#Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.
#Make the change in a copied array without modifying the original array.
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
new_sales=sales_data.copy()
new_sales[stores=="Pune",categories=="Electronics"]=740000
print(new_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [198]:
#Question 71: Revised Beauty Cost
#Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.
#Create an updated cost array.
new_cost_data=cost_data.copy()
cost_per=cost_data*0.08
new_cost=cost_data-cost_per
new_cost_data[:,categories=="Beauty"]=new_cost[:,categories=="Beauty"]
print(cost_data)
print(new_cost_data)


[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [199]:
#Question 72: Furniture Cost Increase
#Furniture costs increase by 12% for all stores.
#Update only the Furniture column.
new_cost_data=cost_data.copy()
cost_per=cost_data*1.12
new_cost=cost_data+cost_per
new_cost_data[:,categories=="Furniture"]=new_cost[:,categories=="Furniture"]
print(new_cost_data)

[[640000 315000 220000 434600 125000 160000]
 [590000 350000 210000 477000 140000 170000]
 [700000 295000 245000 413400 120000 155000]
 [790000 390000 265000 530000 165000 205000]
 [530000 310000 205000 360400 115000 145000]]


In [200]:
#Question 73: Store Closure Simulation
#Assume the Pune store is temporarily closed.
#Remove Pune’s sales and cost data from the analysis using np.delete().
new_sales=sales_data.copy()
new_costs=cost_data.copy()
new_value1=np.delete(new_sales,np.where(stores=="Pune"),axis=0)
new_value2=np.delete(new_costs,np.where(stores=="Pune"),axis=0)
print(new_value1)
print(new_value2)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [201]:
#Question 74: Adding a New Store
#A new Delhi store is opened with the following data:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

In [202]:

import numpy as np
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
new_sales_data=np.vstack((sales_data,delhi_sales))
new_cost_data=np.vstack((cost_data,delhi_cost))
print(new_sales_data)
print(new_cost_data)
new_store=np.append(stores,"Delhi")
print(new_store)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Part 13: Sorting and Ranking

In [203]:
#Question 75: Adding a New Product Category
#SmartMart starts selling Home Appliances.
import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
new_sales=np.column_stack((sales_data,home_appliance_sales))
new_cost=np.column_stack((cost_data,home_appliance_cost))
print(new_sales)
print(new_cost)
new_category=np.append(categories,"Homeappliances")
print(new_category)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Homeappliances']


Part 13: Sorting and Ranking

In [204]:
#Question 76: Sort Stores by Sales
#Sort stores in ascending order based on total sales.
#Display store names and sales totals.
total_sales_data=np.sum(sales_data,axis=1)
sorting_order=np.argsort(total_sales_data)
for index in sorting_order:
  print(stores[index],":",total_sales_data[index])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


In [205]:
#Question 77: Rank Stores by Profit
#Rank stores from highest to lowest total profit.
#Use np.argsort().
profit=np.sum(sales_data-cost_data,axis=1)
sorting_profit=np.argsort(-profit)
for index in sorting_profit:
  print(stores[index],":",profit[index])

Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000


In [206]:
#Question 78: Sort Categories by Revenue
#Sort product categories from highest to lowest total revenue.
revenue=np.sum(sales_data,axis=0)
sorting=np.argsort(-revenue)
for index in sorting:
  print(categories[index],":",revenue[index])

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Sports : 1175000
Beauty : 1010000


In [207]:
#Question 79: Top Three Store-Category Sales
#Find the three highest individual sales values in the complete sales matrix.
#Display their:
#Sales value
#Store name
#Category name
new_sales=sales_data.flatten()
sorting=np.argsort(-new_sales)[0:3]
print(sorting)
for index in sorting:
  row,col=np.unravel_index(index,sales_data.shape)
  print(stores[row],":",categories[col],":",sales_data[row,col])

[18 12  0]
Mumbai : Electronics : 1050000
Chennai : Electronics : 920000
Bengaluru : Electronics : 850000


In [208]:
#Question 80: Bottom Three Profits
#Find the three lowest profit values in the profit matrix
profit=sales_data-cost_data
flattening=profit.flatten()
sorting=np.argsort(flattening)[0:3]
for index in sorting:
  row,col=np.unravel_index(index,profit.shape)
  print(stores[row],categories[col],profit[row,col])

Pune Furniture 55000
Pune Sports 60000
Chennai Sports 60000


Part 14: Statistical Analysis

In [209]:
#Question 81: Sales Statistics
#Calculate the following for the complete sales array:
#Minimum
#Maximum
#Mean
#Median
#Standard deviation
#Variance
#25th percentile
#50th percentile
#75th percentile
print(np.min(sales_data))
print(np.max(sales_data))
print(np.mean(sales_data))
print(np.median(sales_data))
print(np.std(sales_data))
print(np.var(sales_data))
print(np.percentile(sales_data,25))
print(np.percentile(sales_data,50))
print(np.percentile(sales_data,75))

175000
1050000
389166.6666666667
302500.0
230322.53954448793
53048472222.222206
228750.0
302500.0
416250.0


In [210]:
#Question 82: Store-Wise Standard Deviation
#Calculate the sales standard deviation for every store.
#Use this value to determine which store has the most variation between product categories.
standard_deviation=np.std(sales_data,axis=1)
max_store=np.argmax(standard_deviation)
store_name=stores[max_store]
print(store_name)
print(standard_deviation[max_store])

Mumbai
271860.871280391


In [211]:
#Question 83: Category-Wise Standard Deviation
#Determine which product category has the highest variation in sales across stores.
standard_deviation=np.std(sales_data,axis=0)
max_store=np.argmax(standard_deviation)
print(categories[max_store],":",standard_deviation[max_store])


Electronics : 122539.78945632312


In [212]:
#Question 84: Sales Above Company Average
#Calculate the company-wide average sales value.
#Count how many store-category sales values are above this average.
average_sales=np.mean(sales_data)
max_val=sales_data > average_sales
counting_max_val=np.sum(max_val)
print(counting_max_val)


10


In [213]:
#Question 85: Outlier Detection
#Treat any sales value greater than:
#Mean + 1.5 × Standard Deviation
#as a high-value outlier.
#Identify all such sales values.
mean_val=np.mean(sales_data)
std_val=np.std(sales_data)
outlier_val=mean_val+1.5*std_val
counting_outlier=np.where(sales_data > outlier_val)
sales_val=sales_data[counting_outlier]
print(sales_val)

[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

In [214]:
#Question 86: Flatten Sales Data
#Convert the two-dimensional sales array into a one-dimensional array using:
#flatten()
#ravel()
#Explain the difference between the two methods.
usage_flatten=sales_data.flatten()
usage_ravel=sales_data.ravel()
print(sales_data)
print(usage_flatten)
print(usage_ravel)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [215]:
#Question 87: Reshape Sales Data
#Reshape the 5 × 6 sales array into:
#3 × 10
#10 × 3
#2 × 15
#15 × 2
#Verify that no data is lost.
print(sales_data)
sales1=sales_data.reshape(3,10)
sales2=sales_data.reshape(10,3)
sales3=sales_data.reshape(2,15)
sales4=sales_data.reshape(15,2)
print(sales1)
print(sales2)
print(sales3)
print(sales4)
print(sales_data.size)
print(sales1.size)
print(sales2.size)
print(sales3.size)
print(sales4.size)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000 

In [216]:
#Question 88: Transpose Sales Data
#Transpose the sales array so that:
#Rows represent product categories
#Columns represent stores
transpose_val=sales_data.transpose()
print(transpose_val)
print(transpose_val.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


In [217]:
#Question 89: Combined Sales and Cost Array
#Stack sales_data and cost_data vertically.
#Display the resulting shape.
sales_stack=np.vstack((sales_data,cost_data))
print(sales_stack)
print(sales_stack.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


In [218]:
#Question 90: Store-Level Combined Data
#Create a three-dimensional array where:
#First layer contains sales data
#Second layer contains cost data
#Use np.stack().
Display the shape of the new array.
three_d=np.stack((sales_data,cost_data))
print(three_d.shape)

SyntaxError: invalid syntax (1459142109.py, line 6)

Part 16: Missing Data Scenario

In [ ]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [ ]:
#Question 91: Missing Value Detection
#Find:
#Total number of missing values
#Location of missing values
#Stores and categories containing missing values
import numpy as np
total_missing=np.isnan(sales_with_missing)
summation=np.sum(total_missing)
location=np.argwhere(total_missing)
store_name=stores[location]
category_name=categories[location]
print(total_missing)
print(summation)
print(location)
for i,j in location:
  print(stores[i],":",categories[j])

In [ ]:
#Question 92: Replace Missing Values with Zero
#Replace all missing sales values with zero.
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
replacing_val=np.nan_to_num(sales_with_missing,nan=0)
print(replacing_val)

In [ ]:
#Question 92: Replace Missing Values with Zero
#Replace all missing sales values with zero.
average=round(np.nanmean(sales_with_missing),2)
replace_val=np.nan_to_num(sales_with_missing,nan=average)
print(replace_val)

In [219]:
#Question 94: Replace with Category Average
#Replace each missing value with the average sales value of its respective product category.
average_sales=np.nanmean(sales_with_missing,axis=0)
sales_copy=sales_with_missing.copy()
index=np.argwhere(np.isnan(sales_copy))
print(index)
for i,j in index:
  sales_copy[i,j]=average_sales[j]
print(sales_copy)

[[0 2]
 [1 3]
 [3 1]
 [4 4]]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [220]:
#Question 95: Missing Value Impact
#Compare total sales before and after replacing missing values with zero.
sales_sum_without_replacing=np.nansum(sales_with_missing)
replacement_vals=np.nan_to_num(sales_with_missing,nan=0)
sales_sum_with_replacement=np.nansum(replacement_vals)
print(sales_sum_without_replacing)
print(sales_sum_with_replacement)
print("difference:",sales_sum_without_replacing-sales_sum_with_replacement)

10370000.0
10370000.0
difference: 0.0


Part 17: Conditional Business Decisions

In [221]:
#Question 96: Store Performance Labels
#Classify each store based on total sales:
#"Excellent": Total sales above ₹28,00,000
#"Good": Total sales between ₹24,00,000 and ₹28,00,000
#"Needs Improvement": Total sales below ₹24,00,000
#Use np.select().
sales_sum=np.sum(sales_data,axis=1)
# conditions=np.select(
#     [sales_sum > 2800000,
#     (sales_sum>2400000) & (sales_sum <2800000),
#     sales_sum<2400000]),
#          choices=[
#         "excellent",
#         "good"
#         "need improvement"],
#    default="unknow")

result = np.select((sales_sum > 2800000,(sales_sum>2400000) & (sales_sum <2800000),sales_sum < 2400000),
                   ("Excellent","Good","Needs Improvement"),
                   default = "Unknow"
                   )
print(result)

['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


In [222]:
#Question 97: Profitability Classification
#Classify each store-category combination as:
#"Highly Profitable": Profit above ₹2,00,000
#"Profitable": Profit between ₹1,00,000 and ₹2,00,000
#"Low Profit": Profit below ₹1,00,000
#"Loss": Profit below zero
profit=sales_data-cost_data
result = np.select((profit > 200000,(profit>100000) & (profit <200000),profit < 100000,profit<0),
                   ("Highly Profitable","Profitable","Low Profit","Loss"),
                   default = "Unknown"
                   )
print(result)


[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [223]:
#Question 98: Expansion Recommendation
#A store is eligible for expansion when:
#Total sales are above ₹25,00,000
#Total profit is above ₹7,00,000
#Overall profit margin is above 25%
#Identify eligible stores.
total_profit=np.sum(sales_data-cost_data,axis=1)
total_sales=np.sum(sales_data,axis=1)
total_cost=np.sum(cost_data,axis=1)
profit_margin=(total_profit/total_sales)*100
result=((total_sales > 2500000) & (total_profit >700000)&(profit_margin >np.percentile(profit_margin,25)))
print(result)
indices=np.where(result)
print("Result:",indices)
stores_names=stores[indices]
print(stores_names)


[False False False  True False]
Result: (array([3]),)
['Mumbai']


In [224]:
#Question 99: Category Promotion Recommendation
#A product category should receive additional promotion when:
#Average sales are below ₹3,00,000
#Profit margin is above 25%
#Identify the categories that satisfy these conditions.
average=np.mean(sales_data,axis=0)
total_profit=np.sum(sales_data-cost_data,axis=0)
total_sales=np.sum(sales_data,axis=0)
profit_margin=(total_profit/total_sales)*100
result=((average <300000)&(profit_margin>(np.percentile(profit_margin,25))))
print(result)
indices=np.where(result)
category_name=categories[indices]
print("category:",category_name)

[False False False  True  True  True]
category: ['Furniture' 'Beauty' 'Sports']


Question 99: Category Promotion Recommendation
A product category should receive additional promotion when:

Average sales are below ₹3,00,000
Profit margin is above 25%
Identify the categories that satisfy these conditions.

In [225]:
#100
total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
result=((cost_data >250000)&(profit_margin <25))
indices=np.argwhere(result)
print(profit_margin)
print(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])


[[24.70588235 25.         29.03225806 25.45454545 34.21052632 28.88888889]
 [24.35897436 23.91304348 28.81355932 27.41935484 33.33333333 29.16666667]
 [23.91304348 24.35897436 27.94117647 25.         35.13513514 27.90697674]
 [24.76190476 23.52941176 29.33333333 27.53623188 34.         29.31034483]
 [23.1884058  23.45679012 26.78571429 24.44444444 34.28571429 29.26829268]]
[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]
[[0 0]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [4 0]
 [4 1]]
Bengaluru Electronics
Hyderabad Electronics
Hyderabad Groceries
Chennai Electronics
Chennai Groceries
Mumbai Electronics
Mumbai Groceries
Pune Electronics
Pune Groceries


Part 18: Inventory Scenario

In [226]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock
Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [227]:
#101
closing_stock = opening_stock - units_sold
print(closing_stock)


[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification
Identify store-category combinations where closing stock is below 30 units.

In [228]:
#102
closing_stock = opening_stock - units_sold
result=closing_stock < 30
indices=np.argwhere(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])


[[0 0]
 [0 3]
 [1 0]
 [1 3]
 [2 0]
 [2 3]
 [3 0]
 [4 0]
 [4 3]]
Bengaluru Electronics
Bengaluru Furniture
Hyderabad Electronics
Hyderabad Furniture
Chennai Electronics
Chennai Furniture
Mumbai Electronics
Pune Electronics
Pune Furniture


Question 103: Stock Availability Percentage
Calculate the percentage of opening stock that remains unsold.

In [229]:
#103
unsold=opening_stock-units_sold
result=(unsold/opening_stock)*100
print(result)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products
A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [230]:
#104
per_opening=(units_sold/opening_stock)*100
s=np.argwhere(per_opening > 80)
print(s)
for i,j in s:
  print(stores[i],categories[j])

[[0 1]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]
 [3 0]
 [3 1]
 [3 2]
 [4 1]]
Bengaluru Groceries
Hyderabad Groceries
Hyderabad Clothing
Chennai Electronics
Chennai Groceries
Chennai Clothing
Mumbai Electronics
Mumbai Groceries
Mumbai Clothing
Pune Groceries


Question 105: Category-Wise Units Sold
Calculate the total units sold for each product category.

In [231]:
#105
total_units_sold=np.sum(units_sold,axis=0)
print(total_units_sold)

[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold
Calculate total units sold by each store.

In [232]:
#106
total_units_sold=np.sum(units_sold,axis=1)
print(total_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales
Identify the store that sold the highest total number of units.

In [233]:
#107
store_names=np.sum(units_sold,axis=1)
indices=np.argmax(store_names)
print(indices)
print(stores[indices])

3
Mumbai


Question 108: Reorder Requirement
A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [234]:
#108
closing_stock = opening_stock - units_sold
reordering=closing_stock < 25
print(reordering)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity
Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [235]:
#109
closing_stock=opening_stock-units_sold
result=np.where(closing_stock < 25,100-closing_stock,0)
print(result)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales
Calculate cumulative category sales for each store using np.cumsum().

In [236]:
#110
cumulative_sales=np.cumsum(sales_data,axis=1)
print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales
Flatten the sales array and calculate cumulative company sales.

In [237]:
#111
flattening=sales_data.flatten()
cumulative_sales=np.cumsum(flattening)
print(cumulative_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories
Calculate the difference between consecutive category sales for each store using np.diff().

In [238]:
#112
result=np.diff(sales_data,axis=1)
print(result)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values
Find all unique sales values in sales_data.

Also count the frequency of each value.

In [239]:
#113
unique_vals=np.unique(sales_data)
print(unique_vals)
counting=np.unique(unique_vals,return_counts=True)
print(counting)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
(array([ 175000,  185000,  190000,  205000,  210000,  215000,  225000,
        240000,  250000,  260000,  275000,  280000,  290000,  295000,
        310000,  340000,  345000,  375000,  390000,  405000,  420000,
        460000,  510000,  690000,  780000,  850000,  920000, 1050000]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))


Question 114: Search for Specific Sales
Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [240]:
#114
result=np.argwhere(sales_data==420000)
print(result)

[[0 1]]


Question 115: Compare Sales and Cost
Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [241]:
#115
result=(sales_data > cost_data)
indices=np.argwhere(result)
print(indices)
profitabble=np.all(result)
print(profitabble)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]]
True


Question 116: Clip Profit Values
For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000
Maximum: ₹2,50,000
Use np.clip() to create a reporting profit array.

In [242]:
#116
result=(sales_data > cost_data)
indices=np.argwhere(result)
print(indices)
profitabble=np.all(result)
print(profitabble)

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]]
True


Question 117: Normalize Sales Data
Normalize all sales values using min-max normalization:

Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [243]:
#117
normalized_sales=(sales_data - np.min(sales_data))/(np.max(sales_data - np.min(sales_data)))
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data
Standardize sales using:

Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [244]:
#118
standard_sales=((sales_data - np.mean(sales_data))/(np.std(sales_data)))
print(standard_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values
Convert profit margin values into:

Two decimal places
Nearest whole number
Floor values
Ceiling values

In [245]:
#119
total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
print(np.round(profit_margin,2))
print(np.round(profit_margin))
print(np.floor(profit_margin))
print(np.ceil(profit_margin))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data
Save the following arrays as NumPy binary files:

sales_data.npy
cost_data.npy
profit_data.npy
Load them back and verify that the loaded arrays are equal to the original arrays.

In [246]:
#120
profit_data=sales_data-cost_data
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)
np.load("sales_data.npy")
np.load("cost_data.npy")
np.load("profit_data.npy")

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

Part 20: Final Retail Analytics Project
Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

In [247]:
np.load("cost_data.npy")

array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [248]:
import numpy as np
# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [249]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
target_achieved1=np.sum(sales_data>sales_targets,axis=1)
target_achieved2=np.sum(sales_data>sales_targets,axis=0)

In [250]:
print("SMART RETAIL PERFORMANCE REPORT")
print("=====================================")
print("COMPANY SUMMARY")
print("------------------------------------------")
print("Total Sales:",np.sum(sales_data))
print("Total Cost:",np.sum(cost_data))
print("Total_Profit:",np.sum(profit))
print("Profit Margin:",np.sum(profit_margin))
print("Average:",np.mean(sales_data))
print("Highest Sales:",np.max(sales_data))
print("Lowest Sales:",np.min(sales_data))
print("\nSTORE SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=1))
print("Total Cost:",np.sum(cost_data,axis=1))
print("Total Profit:",np.sum(profit,axis=1))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=1),2))
print("No Of Targets Achieved:",target_achieved1)
print("Units Sold:",np.sum(units_sold,axis=1))
print("\nCATEGORY SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=0))
print("Total Cost:",np.sum(cost_data,axis=0))
print("Total Profit:",np.sum(profit,axis=0))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=0),2))
print("No Of Targets Achieved:",target_achieved2)
print("Units Sold:",np.sum(units_sold,axis=0))
print("Average:",np.mean(sales_data,axis=0))
print("\nMANAGEMENT RECOMMENDATIONS")
print("=====================================")
print("\nBEST PERFORMING STORE")
print("------------------------------------------")

SMART RETAIL PERFORMANCE REPORT
COMPANY SUMMARY
------------------------------------------
Total Sales: 11675000
Total Cost: 8600000
Total_Profit: 3075000
Profit Margin: 828.4529274527509
Average: 389166.6666666667
Highest Sales: 1050000
Lowest Sales: 175000

STORE SUMMARY
-------------------------------------
Total Sales: [2270000 2295000 2310000 2820000 1980000]
Total Cost: [1665000 1685000 1710000 2065000 1475000]
Total Profit: [605000 610000 600000 755000 505000]
Profit Margin: [167.29 167.   164.26 168.47 161.43]
No Of Targets Achieved: [1 4 2 6 0]
Units Sold: [1110 1175 1095 1390  950]

CATEGORY SUMMARY
-------------------------------------
Total Sales: [4290000 2185000 1600000 1415000 1010000 1175000]
Total Cost: [3250000 1660000 1145000 1045000  665000  835000]
Total Profit: [1040000  525000  455000  370000  345000  340000]
Profit Margin: [120.93 120.26 141.91 129.85 170.96 144.54]
No Of Targets Achieved: [3 2 2 2 2 2]
Units Sold: [ 485 1950 1240  345  980  720]
Average: [85800